### ISSUE TITLE
Unable to Setup

### ISSUE THREAD

**Issue by stormikph** [epicweb-dev/full-stack-foundations#49]
When I try to start up and I'm received this error 
`npm run setup`
<img width="718" alt="Screenshot 2023-10-24 at 7 49 35 PM" src="https://github.com/epicweb-dev/full-stack-foundations/assets/65935341/bdf16af0-e94c-43db-af8c-9f4925f25afa">

`npm i`
<img width="404" alt="Screenshot 2023-10-24 at 7 54 09 PM" src="https://github.com/epicweb-dev/full-stack-foundations/assets/65935341/597fc132-efea-4c33-a883-1820f274ba42">

`npm start`
<img width="721" alt="Screenshot 2023-10-24 at 7 55 02 PM" src="https://github.com/epicweb-dev/full-stack-foundations/assets/65935341/dd3ecf95-c2b0-4e1a-af3a-a4490ce6bdea">

git version: 2.26.2
node version: 18.18.2
npm version: 9.8.1

**Comment by kentcdodds** [comment]
Looks like something is wrong with your system because that error says your version of node is 15

**Comment by ng-hai** [comment]
Hi @kentcdodds, I'm running into this issue as well. The error happens because of `nvm`, NVM detects that the repo does not contain any `.nvmrc` , so it reverts to the default version

<img width="1136" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/19520278/113f6fdd-1461-4fbd-92d8-c3de371068d4">

Here are my approaches to fix this issue:
1. Add `.nvmrc` to the repo containing the required Node version
2. Let the users fix themself (I do this)

<img width="1136" alt="image" src="https://github.com/epicweb-dev/full-stack-foundations/assets/19520278/071b619e-ba37-49a6-aa3b-512fd51336c9">

**Comment by kentcdodds** [comment]
I don't plan on adding an `.nvmrc` file. There are multiple ways people manage their node version and I'm not interested in adding a config file for every one of them.

I recommend you uninstall node v16 in your node version manager as that is no longer a maintained version of node.

**Comment by ng-hai** [comment]
Agree.

**Comment by zoranstankovic** [comment]
When I tried to run `npm run setup` I got this error:
![playwritgh_error](https://github.com/epicweb-dev/full-stack-foundations/assets/6569042/c7adf2cd-d98b-4336-bc89-fc2225767d0c)
I am using Linux Mint, and I found that there is an issue with Playwright here: https://github.com/microsoft/playwright/issues/6554
Also, there is no possibility of running this workshop if you don't use one of those systems:
```
System requirements from https://playwright.dev/docs/intro

    Node.js 16+
    Windows 10+, Windows Server 2016+ or Windows Subsystem for Linux (WSL).
    MacOS 12 Monterey or MacOS 13 Ventura.
    Debian 11, Debian 12, Ubuntu 20.04 or Ubuntu 22.04, with x86-64 or arm64 architecture.
```
I also tried before on Arch Linux and had another issue with the Playwright part.
Is there any workaround for this problem?
Thank you in advance.

**Comment by kentcdodds** [comment]
Sadly playwright does not support your version of linux. You'll have to disable the playwright setup by running setup with [`SKIP_PLAYWRIGHT`](https://github.com/epicweb-dev/full-stack-foundations/blob/592c0c87a76c10096e5094e938fa6f070e7e3858/scripts/setup-custom.js#L43):

```
SKIP_PLAYWRIGHT=true npm run setup
```

You'll want to do the same for all the workshops. Unfortunately this won't work for the testing workshop because playwright is an important part of those exercises, but you could run the workshops in [GitHub Codespaces](https://github.com/codespaces) which can run the non-UI mode of Playwright.

Hopefully playwright will support linux mint in the future.
