### ISSUE TITLE
Unable to push my changes to my Github account repo.

### ISSUE THREAD

**Issue by s4sachin** [epicweb-dev/full-stack-foundations#97]
I have cloned the Full Stack Foundations repo and have started working on it. I am facing the following problems in connecting my local repo with my personal remote repo.

> First the changes are not getting detected 
> Even though i have set remote to my repo url, i am not able to push any changes

This is the error I am getting-

> git push -u origin main                                                                                        ─╯
Enumerating objects: 602, done.
Counting objects: 100% (602/602), done.
Delta compression using up to 8 threads
Compressing objects: 100% (285/285), done.
Writing objects: 100% (602/602), 1.16 MiB | 4.23 MiB/s, done.
Total 602 (delta 299), reused 596 (delta 297), pack-reused 0
remote: Resolving deltas: 100% (299/299), done.
remote: fatal: did not receive expected object 67f41621aa416c748bef8b3acf27c2ba4cabb428
error: remote unpack failed: index-pack failed
To github.com:s4sachin/Full-Stack-App.git
 ! [remote rejected] main -> main (failed)
error: failed to push some refs to 'github.com:s4sachin/Full-Stack-App.git'

**Comment by kentcdodds** [comment]
This looks like some issue with your machine and its git setup. 

But I have good news! There's no reason you need to commit changes to the repo. The way this workshop is set up, you won't be needing to keep changes to the repo because all your workshop work should happen inside the playground directory which is gitignored! Please make sure to watch the onboarding video first: https://epicweb.dev/get-started

Cheers!
